// This file is generated from the versioned remote avatar archive. Keep its
// filenames and gender metadata in sync when publishing a new avatar version.
import type { AvatarGender } from './avatarCatalog';
import { getRemoteAvatarUrl } from './avatarRemote';

export interface GeneratedNpcAvatarAsset {
  name: string;
  gender: AvatarGender;
  src: string;
}

function getGeneratedAvatarUrl(name: string): string {
  return getRemoteAvatarUrl('generated', `${name}.jpg`);
}

export const GENERATED_NPC_AVATAR_ASSETS: GeneratedNpcAvatarAsset[] = [
  { name: '一灯大师', gender: '男', src: getGeneratedAvatarUrl('一灯大师') },
  { name: '丘处机', gender: '男', src: getGeneratedAvatarUrl('丘处机') },
  { name: '丧门鬼', gender: '男', src: getGeneratedAvatarUrl('丧门鬼') },
  { name: '侯通海', gender: '男', src: getGeneratedAvatarUrl('侯通海') },
  { name: '俏鬼', gender: '女', src: getGeneratedAvatarUrl('俏鬼') },
  { name: '催命鬼', gender: '男', src: getGeneratedAvatarUrl('催命鬼') },
  { name: '傻姑', gender: '女', src: getGeneratedAvatarUrl('傻姑') },
  { name: '全金发', gender: '男', src: getGeneratedAvatarUrl('全金发') },
  { name: '公孙止', gender: '男', src: getGeneratedAvatarUrl('公孙止') },
  { name: '公孙绿萼', gender: '女', src: getGeneratedAvatarUrl('公孙绿萼') },
  { name: '冯默风', gender: '男', src: getGeneratedAvatarUrl('冯默风') },
  { name: '刘处玄', gender: '男', src: getGeneratedAvatarUrl('刘处玄') },
  { name: '包惜弱', gender: '女', src: getGeneratedAvatarUrl('包惜弱') },
  { name: '华筝', gender: '女', src: getGeneratedAvatarUrl('华筝') },
  { name: '南希仁', gender: '男', src: getGeneratedAvatarUrl('南希仁') },
  { name: '史仲猛', gender: '男', src: getGeneratedAvatarUrl('史仲猛') },
  { name: '史伯威', gender: '男', src: getGeneratedAvatarUrl('史伯威') },
  { name: '史叔刚', gender: '男', src: getGeneratedAvatarUrl('史叔刚') },
  { name: '史孟捷', gender: '男', src: getGeneratedAvatarUrl('史孟捷') },
  { name: '史季强', gender: '男', src: getGeneratedAvatarUrl('史季强') },
  { name: '吊死鬼', gender: '女', src: getGeneratedAvatarUrl('吊死鬼') },
  { name: '吕文德', gender: '男', src: getGeneratedAvatarUrl('吕文德') },
  { name: '吴青烈', gender: '男', src: getGeneratedAvatarUrl('吴青烈') },
  { name: '周伯通', gender: '男', src: getGeneratedAvatarUrl('周伯通') },
  { name: '哲别', gender: '男', src: getGeneratedAvatarUrl('哲别') },
  { name: '大头鬼', gender: '男', src: getGeneratedAvatarUrl('大头鬼') },
  { name: '天竺僧', gender: '男', src: getGeneratedAvatarUrl('天竺僧') },
  { name: '姬清虚', gender: '男', src: getGeneratedAvatarUrl('姬清虚') },
  { name: '孙不二', gender: '女', src: getGeneratedAvatarUrl('孙不二') },
  { name: '孙婆婆', gender: '女', src: getGeneratedAvatarUrl('孙婆婆') },
  { name: '宋五', gender: '男', src: getGeneratedAvatarUrl('宋五') },
  { name: '完颜洪烈', gender: '男', src: getGeneratedAvatarUrl('完颜洪烈') },
  { name: '完颜萍', gender: '女', src: getGeneratedAvatarUrl('完颜萍') },
  { name: '小龙女', gender: '女', src: getGeneratedAvatarUrl('小龙女') },
  { name: '尹克西', gender: '男', src: getGeneratedAvatarUrl('尹克西') },
  { name: '尹志平', gender: '男', src: getGeneratedAvatarUrl('尹志平') },
  { name: '尼摩星', gender: '男', src: getGeneratedAvatarUrl('尼摩星') },
  { name: '张君宝', gender: '男', src: getGeneratedAvatarUrl('张君宝') },
  { name: '张阿生', gender: '男', src: getGeneratedAvatarUrl('张阿生') },
  { name: '彭连虎', gender: '男', src: getGeneratedAvatarUrl('彭连虎') },
  { name: '彭长老', gender: '男', src: getGeneratedAvatarUrl('彭长老') },
  { name: '忽必烈', gender: '男', src: getGeneratedAvatarUrl('忽必烈') },
  { name: '拖雷', gender: '男', src: getGeneratedAvatarUrl('拖雷') },
  { name: '无常鬼', gender: '男', src: getGeneratedAvatarUrl('无常鬼') },
  { name: '曲三', gender: '男', src: getGeneratedAvatarUrl('曲三') },
  { name: '札木合', gender: '男', src: getGeneratedAvatarUrl('札木合') },
  { name: '朱子柳', gender: '男', src: getGeneratedAvatarUrl('朱子柳') },
  { name: '朱聪', gender: '男', src: getGeneratedAvatarUrl('朱聪') },
  { name: '李志常', gender: '男', src: getGeneratedAvatarUrl('李志常') },
  { name: '李莫愁', gender: '女', src: getGeneratedAvatarUrl('李莫愁') },
  { name: '李萍', gender: '女', src: getGeneratedAvatarUrl('李萍') },
  { name: '杨康', gender: '男', src: getGeneratedAvatarUrl('杨康') },
  { name: '杨过', gender: '男', src: getGeneratedAvatarUrl('杨过') },
  { name: '杨铁心', gender: '男', src: getGeneratedAvatarUrl('杨铁心') },
  { name: '柯镇恶', gender: '男', src: getGeneratedAvatarUrl('柯镇恶') },
  { name: '桑昆', gender: '男', src: getGeneratedAvatarUrl('桑昆') },
  { name: '梁子翁', gender: '男', src: getGeneratedAvatarUrl('梁子翁') },
  { name: '梁长老', gender: '男', src: getGeneratedAvatarUrl('梁长老') },
  { name: '梅超风', gender: '女', src: getGeneratedAvatarUrl('梅超风') },
  { name: '樊一翁', gender: '男', src: getGeneratedAvatarUrl('樊一翁') },
  { name: '樵夫', gender: '男', src: getGeneratedAvatarUrl('樵夫') },
  { name: '欧阳克', gender: '男', src: getGeneratedAvatarUrl('欧阳克') },
  { name: '欧阳锋', gender: '男', src: getGeneratedAvatarUrl('欧阳锋') },
  { name: '武三娘', gender: '女', src: getGeneratedAvatarUrl('武三娘') },
  { name: '武三通', gender: '男', src: getGeneratedAvatarUrl('武三通') },
  { name: '武修文', gender: '男', src: getGeneratedAvatarUrl('武修文') },
  { name: '武敦儒', gender: '男', src: getGeneratedAvatarUrl('武敦儒') },
  { name: '段天德', gender: '男', src: getGeneratedAvatarUrl('段天德') },
  { name: '沈青刚', gender: '男', src: getGeneratedAvatarUrl('沈青刚') },
  { name: '沙通天', gender: '男', src: getGeneratedAvatarUrl('沙通天') },
  { name: '泗水渔隐', gender: '男', src: getGeneratedAvatarUrl('泗水渔隐') },
  { name: '洪七公', gender: '男', src: getGeneratedAvatarUrl('洪七公') },
  { name: '洪凌波', gender: '女', src: getGeneratedAvatarUrl('洪凌波') },
  { name: '潇湘子', gender: '男', src: getGeneratedAvatarUrl('潇湘子') },
  { name: '灵智上人', gender: '男', src: getGeneratedAvatarUrl('灵智上人') },
  { name: '煞神鬼', gender: '男', src: getGeneratedAvatarUrl('煞神鬼') },
  { name: '王坚', gender: '男', src: getGeneratedAvatarUrl('王坚') },
  { name: '王处一', gender: '男', src: getGeneratedAvatarUrl('王处一') },
  { name: '王志坦', gender: '男', src: getGeneratedAvatarUrl('王志坦') },
  { name: '王罕', gender: '男', src: getGeneratedAvatarUrl('王罕') },
  { name: '瑛姑', gender: '女', src: getGeneratedAvatarUrl('瑛姑') },
  { name: '瘦丐', gender: '男', src: getGeneratedAvatarUrl('瘦丐') },
  { name: '皮清玄', gender: '男', src: getGeneratedAvatarUrl('皮清玄') },
  { name: '神雕', gender: '男', src: getGeneratedAvatarUrl('神雕') },
  { name: '程瑶迦', gender: '女', src: getGeneratedAvatarUrl('程瑶迦') },
  { name: '程英', gender: '女', src: getGeneratedAvatarUrl('程英') },
  { name: '穆念慈', gender: '女', src: getGeneratedAvatarUrl('穆念慈') },
  { name: '笑脸鬼', gender: '男', src: getGeneratedAvatarUrl('笑脸鬼') },
  { name: '简长老', gender: '男', src: getGeneratedAvatarUrl('简长老') },
  { name: '耶律楚材', gender: '男', src: getGeneratedAvatarUrl('耶律楚材') },
  { name: '耶律燕', gender: '女', src: getGeneratedAvatarUrl('耶律燕') },
  { name: '耶律齐', gender: '男', src: getGeneratedAvatarUrl('耶律齐') },
  { name: '蒙哥', gender: '男', src: getGeneratedAvatarUrl('蒙哥') },
  { name: '裘千仞', gender: '男', src: getGeneratedAvatarUrl('裘千仞') },
  { name: '裘千尺', gender: '女', src: getGeneratedAvatarUrl('裘千尺') },
  { name: '觉远', gender: '男', src: getGeneratedAvatarUrl('觉远') },
  { name: '讨债鬼', gender: '男', src: getGeneratedAvatarUrl('讨债鬼') },
  { name: '谭处端', gender: '男', src: getGeneratedAvatarUrl('谭处端') },
  { name: '赵志敬', gender: '男', src: getGeneratedAvatarUrl('赵志敬') },
  { name: '达尔巴', gender: '男', src: getGeneratedAvatarUrl('达尔巴') },
  { name: '郝大通', gender: '男', src: getGeneratedAvatarUrl('郝大通') },
  { name: '郭啸天', gender: '男', src: getGeneratedAvatarUrl('郭啸天') },
  { name: '郭破虏', gender: '男', src: getGeneratedAvatarUrl('郭破虏') },
  { name: '郭芙', gender: '女', src: getGeneratedAvatarUrl('郭芙') },
  { name: '郭襄', gender: '女', src: getGeneratedAvatarUrl('郭襄') },
  { name: '郭靖', gender: '男', src: getGeneratedAvatarUrl('郭靖') },
  { name: '都史', gender: '男', src: getGeneratedAvatarUrl('都史') },
  { name: '金轮法王', gender: '男', src: getGeneratedAvatarUrl('金轮法王') },
  { name: '钱青健', gender: '男', src: getGeneratedAvatarUrl('钱青健') },
  { name: '铁木真', gender: '男', src: getGeneratedAvatarUrl('铁木真') },
  { name: '长须鬼', gender: '男', src: getGeneratedAvatarUrl('长须鬼') },
  { name: '陆乘风', gender: '男', src: getGeneratedAvatarUrl('陆乘风') },
  { name: '陆冠英', gender: '男', src: getGeneratedAvatarUrl('陆冠英') },
  { name: '陆无双', gender: '女', src: getGeneratedAvatarUrl('陆无双') },
  { name: '陆立鼎', gender: '男', src: getGeneratedAvatarUrl('陆立鼎') },
  { name: '霍都', gender: '男', src: getGeneratedAvatarUrl('霍都') },
  { name: '韩宝驹', gender: '男', src: getGeneratedAvatarUrl('韩宝驹') },
  { name: '韩小莹', gender: '女', src: getGeneratedAvatarUrl('韩小莹') },
  { name: '马光佐', gender: '男', src: getGeneratedAvatarUrl('马光佐') },
  { name: '马钰', gender: '男', src: getGeneratedAvatarUrl('马钰') },
  { name: '马青雄', gender: '男', src: getGeneratedAvatarUrl('马青雄') },
  { name: '鲁有脚', gender: '男', src: getGeneratedAvatarUrl('鲁有脚') },
  { name: '鹿清笃', gender: '男', src: getGeneratedAvatarUrl('鹿清笃') },
  { name: '黄药师', gender: '男', src: getGeneratedAvatarUrl('黄药师') },
  { name: '黄蓉', gender: '女', src: getGeneratedAvatarUrl('黄蓉') },
  { name: '黎生', gender: '男', src: getGeneratedAvatarUrl('黎生') },
];
