/**
 * 人物特质数据库（草稿/完整重构方案）
 *
 * 统一规范：
 * - 品阶与花费：
 *   粗浅(白): 3点 | 传家(绿): 8点 | 上乘(蓝): 14点 | 镇派(紫): 18点 | 绝世(金): 24点 | 传说(红): 30点
 *   缺陷(负面): 轻度 -3点 | 中度 -6点 | 重度/断门 -10点 | 绝灭 -20点
 * - 分类：天资 | 体质 | 性情 | 气质 | 命格 | 缺陷 （彻底移除“经历”与“专长”）
 * - 核心设计原则：
 *   1. 拒绝为了凑数强塞属性与特质，很多风味/人际特质纯靠 Prompt 驱动即可，无需生硬堆砌属性。
 *   2. 风格化加成：身体轻灵/厚重直接辐射到对应风格的武学，而非狭隘限制单一兵刃。
 *   3. 经典趣味特质合理古雅化与提炼（魏武遗风、移花接木、债多不压身、恋爱脑、纯路人等）。
 *   4. 【断根绝阳】作为-10点负面缺陷，通过属性小调整与严谨的 Prompt 引导大模型限制情缘与纯阳童子功。
 */

import type {
  CharacterTrait,
  InitialAttributes,
  TraitAttributeModifiers,
  TraitRestrictions,
  TraitDiscounts,
  TraitRank,
  TraitCategory,
} from '../types';
import type { AttributeModifierSource } from './attributeCalculator';

const COMBAT_RULE_PROMPT =
  '该特质的战力与属性数值已完全折算进属性面板中，战斗胜负严格以面板与境界为准；只可在非战力的日常言行、风味描写与江湖交互中展现特异异象与角色个性。';

/**
 * 普通人物特质常量列表（重构草稿）
 */
export const CHARACTER_TRAITS_DRAFT: CharacterTrait[] = [
  // ============================================
  // 1. 武道天资与风格（天资）
  // ============================================
  // 剑法专精
  {
    name: '剑痴',
    rank: '传家',
    category: '性情',
    cost: 8,
    description: '对剑有着近乎偏执的痴迷，研习剑法事半功倍，但对其他兵刃兴致缺缺。',
    discounts: { martialTypeDiscount: { 剑法: 0.25 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '剑心通明',
    rank: '镇派',
    category: '天资',
    cost: 18,
    description: '生具剑心，对于剑路虚实与剑势脉络异常敏锐，研习剑经时往往能早一步参透关窍。',
    attributeModifiers: { 洞察: 15 },
    discounts: { martialTypeDiscount: { 剑法: 0.2 } },
    flavorPrompt: '观剑极具慧眼，能捕捉剑路转折之精微，但不能凭特质直接看穿高深武学或越级取胜。',
  },

  // 风格化武道：轻灵 vs 沉重
  {
    name: '身手矫捷',
    rank: '上乘',
    category: '天资',
    cost: 14,
    description: '身形轻捷，手随心运，擅长一切走轻灵巧变一路的武学与兵刃。',
    attributeModifiers: { 机敏: 15 },
    discounts: { martialTypeDiscount: { 剑法: 0.15, 暗器: 0.15, 轻功: 0.15 } },
    flavorPrompt: '举手投足灵秀轻捷，出招转换毫无滞涩；战力仍以属性与所学武功为准。',
  },
  {
    name: '沉岳重劲',
    rank: '上乘',
    category: '体质',
    cost: 14,
    description: '骨重筋强，身藏沉岳之劲，天生适合驾驭厚拙沉兵与大开大阖的刚猛劲力。',
    attributeModifiers: { 臂力: 15 },
    discounts: { martialTypeDiscount: { 刀法: 0.15, 枪戟: 0.15, 拳掌: 0.15 } },
    flavorPrompt: '举重若轻，渊渟岳峙，以浑厚沉劲见长；战力仍以属性与所学武功为准。',
  },

  // 战场与长兵搏杀
  {
    name: '嗜战如狂',
    rank: '传家',
    category: '性情',
    cost: 8,
    description: '性情好勇斗狠，越逢强敌越容易全神贯注，对凶猛直接的劈砍冲杀有异乎常人的热情。',
    attributeModifiers: { 臂力: 10 },
    discounts: { martialTypeDiscount: { 刀法: 0.2, 枪戟: 0.2 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '沙场本能',
    rank: '传家',
    category: '天资',
    cost: 8,
    description: '面对多人围逼临危不乱，擅察群敌进退方位，极善利用丈八长兵的空间之利掌控方圆。',
    attributeModifiers: { 臂力: 10 },
    discounts: { martialTypeDiscount: { 枪戟: 0.25 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '临阵无惧',
    rank: '镇派',
    category: '性情',
    cost: 18,
    description: '泰山崩于前而色不变，身陷重围之时心境愈发沉稳，毫无畏难怯战之意。',
    attributeModifiers: { 臂力: 15, 气血: 10 },
    discounts: { martialTypeDiscount: { 枪戟: 0.2, 刀法: 0.15 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // 拳掌与暗器机巧
  {
    name: '铁拳天成',
    rank: '传家',
    category: '体质',
    cost: 8,
    description: '掌骨坚厚，腕肘硬朗，天生一副修炼外家拳掌功夫的强健体格。',
    attributeModifiers: { 臂力: 10 },
    discounts: { martialTypeDiscount: { 拳掌: 0.25 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '弹指生风',
    rank: '粗浅',
    category: '天资',
    cost: 3,
    description: '指腕机巧灵活，指劲拿捏妙至颠毫，随手飞掷石子暗器便具破空之势。',
    discounts: { martialTypeDiscount: { 暗器: 0.15 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '心灵手巧',
    rank: '粗浅',
    category: '天资',
    cost: 3,
    description: '十指纤细灵活，擅长开锁、拆装机括与细致手工，操控暗器机括亦有天赋。',
    discounts: { martialTypeDiscount: { 暗器: 0.1 } },
    flavorPrompt: '手脚麻利细密，善于拨弄细小机括与暗锁。',
  },
  {
    name: '袖中藏锋',
    rank: '上乘',
    category: '天资',
    cost: 14,
    description: '十指如兰花弄影，精通细微机括藏纳与拆解，于袖箭、飞针等隐蔽暗器上手极快。',
    attributeModifiers: { 洞察: 10, 机敏: 10 },
    discounts: { martialTypeDiscount: { 暗器: 0.2 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // 身法轻功与全武道通识
  {
    name: '草上飞',
    rank: '粗浅',
    category: '天资',
    cost: 3,
    description: '下盘轻快灵巧，折转腾挪极具天分，跋山涉水或穿街过巷如履平地。',
    discounts: { martialTypeDiscount: { 轻功: 0.15 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '身轻如燕',
    rank: '传家',
    category: '体质',
    cost: 8,
    description: '身骨轻灵若无物，掠水踏叶不留痕，修习高深提纵身法极易领会其中关窍。',
    attributeModifiers: { 机敏: 10 },
    discounts: { martialTypeDiscount: { 轻功: 0.25 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '临机迅捷',
    rank: '上乘',
    category: '天资',
    cost: 14,
    description: '灵台警觉，应变若电，遭逢猝变之际机断立决，绝无分秒迟滞。',
    attributeModifiers: { 机敏: 15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '触类旁通',
    rank: '传家',
    category: '天资',
    cost: 8,
    description: '武学悟性出众，举一反三，研习招式效率过人。',
    discounts: { savvyRequirementOffset: -1 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '嗜武如命',
    rank: '上乘',
    category: '性情',
    cost: 14,
    description: '将武道视为生命，无时无刻不在揣摩切磋，全流派功法精进速度均获得提升。',
    discounts: { globalUpgradeDiscount: 0.1 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '武学奇才',
    rank: '镇派',
    category: '天资',
    cost: 18,
    description: '天生百脉具通的绝代奇才，任何深奥武功一看便懂，极难遇到修炼瓶颈。',
    discounts: { savvyRequirementOffset: -2, globalUpgradeDiscount: 0.15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // ============================================
  // 2. 肉身体魄与经脉内息（体质 / 医毒）
  // ============================================
  {
    name: '体魄强健',
    rank: '粗浅',
    category: '体质',
    cost: 3,
    description: '生来体格健壮，气血充沛，比常人更能经受风霜劳苦。',
    attributeModifiers: { 根骨: 10, 气血: 10 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '铜皮铁骨',
    rank: '传家',
    category: '体质',
    cost: 8,
    description: '天生筋厚骨密，肉搏摔打之下耐受远胜常人，不惧寻常刀棍磕碰。',
    attributeModifiers: { 根骨: 15, 气血: 15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '金刚不坏',
    rank: '镇派',
    category: '体质',
    cost: 18,
    description: '筋骨若精钢交铸，气血如烘炉初沸，是百里挑一的外家横练巅峰胚子。',
    attributeModifiers: { 根骨: 25, 气血: 25 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '丹田气海',
    rank: '传家',
    category: '体质',
    cost: 8,
    description: '天生气海宽厚渊深，经络通达，运功调息时真气沛然莫御。',
    attributeModifiers: { 内力: 15 },
    discounts: { martialTypeDiscount: { 内功: 0.15 } },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '九阳之体',
    rank: '绝世',
    category: '体质',
    cost: 24,
    description: '天生纯阳经脉，阳气如日中天，是修炼至阳武学的绝佳体质，诸邪难侵。',
    attributeModifiers: { 内力: 25, 气血: 20 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '至阴之体',
    rank: '绝世',
    category: '体质',
    cost: 24,
    description: '体质阴寒玄幽，内息冷冽如霜，极利于修习阴柔与幽微武学。',
    attributeModifiers: { 内力: 25, 机敏: 15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '紫气东来',
    rank: '传说',
    category: '体质',
    cost: 30,
    description: '先天道门灵胎，每日清晨吞吐朝霞紫气，百脉温润无瑕，内息纯阳浩然。',
    attributeModifiers: { 内力: 30, 根骨: 20, 气血: 20 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '尝药辨草',
    rank: '粗浅',
    category: '天资',
    cost: 3,
    description: '略识百草药性，采集山野药材时偶能辨识良药，对医理有天然灵性。',
    flavorPrompt: '见草木便下意识掐闻辨味，口尝药性习以为常。',
  },
  {
    name: '药王转世',
    rank: '上乘',
    category: '天资',
    cost: 14,
    description: '对药性、脉象与人体经络参悟极快，研习医理药道往往能触类旁通，丹药吸收更佳。',
    attributeModifiers: { 气血: 10, 内力: 10 },
    flavorPrompt: '望闻问切信手拈来，对各门派毒伤病患胸有成竹。',
  },
  {
    name: '百毒不侵',
    rank: '上乘',
    category: '体质',
    cost: 14,
    description: '体质奇异或服食过天地奇草，寻常草木蛇蝎剧毒入口如饮寻常茶汤。',
    attributeModifiers: { 根骨: 15 },
    flavorPrompt: '见毒物面不改色，寻常蒙汗药砒霜入腹毫无波澜。',
  },
  {
    name: '万毒归宗',
    rank: '镇派',
    category: '体质',
    cost: 18,
    description: '以身纳毒淬炼肉身，周身血液化为剧毒，筋脉对诸多剧毒产生免疫适应。',
    attributeModifiers: { 气血: 15, 内力: 15 },
    flavorPrompt: '体带幽微草药苦香，血色隐泛乌紫，寻常蚊蝇沾体即毙。',
  },
  {
    name: '本命蛊王',
    rank: '绝世',
    category: '体质',
    cost: 24,
    description: '体内育有一尊性命相连的南疆蛊王，蛊脉与心脉相连，遇险自发护体长鸣。',
    attributeModifiers: { 气血: 20, 根骨: 15 },
    flavorPrompt: '心房常有微弱异样律动，遇剧毒恶障蛊虫自发护体长鸣。',
  },

  // ============================================
  // 3. 情爱风月与人际魅力
  // ============================================
  {
    name: '暗送秋波',
    rank: '粗浅',
    category: '气质',
    cost: 3,
    description: '眉目含情，善解人意，面对有婚约或心仪之异性时更易拉近私下关系。',
    flavorPrompt: '面对有伴侣的异性交谈时常带自然撩拨，言语得体不易引起戒心。',
  },
  {
    name: '眉清目秀',
    rank: '粗浅',
    category: '气质',
    cost: 3,
    description: '长相干净讨喜，初见之时容易获得江湖长辈与市井豪客的好感照拂。',
    flavorPrompt: '相貌清秀端正，日常问路打听消息时NPC态度亲和耐烦。',
  },
  {
    name: '红颜知己',
    rank: '传家',
    category: '性情',
    cost: 8,
    description: '极擅倾听异性在伴侣面前无法启齿的委屈，善于在他人情感裂隙中获得深厚信任。',
    flavorPrompt: '异性极易视其为知心良友，倾诉夫妻隔阂，剧情中极擅充当感情倾诉对象。',
  },
  {
    name: '移花接木',
    rank: '传家',
    category: '性情',
    cost: 8,
    description: '抚养仇人或伴侣与他人之子毫无芥蒂，后代极具孝心成材，受江湖敬仰。',
    flavorPrompt: '胸襟开阔不拘小节，剧情中常以仁义宽厚长辈形象为人称道。',
  },
  {
    name: '情殇砺志',
    rank: '传家',
    category: '命格',
    cost: 8,
    description: '命中注定情路多舛，伴侣易生变故或离去；然而痛失所爱时化悲痛为苦修动力，修为进境神速。',
    flavorPrompt: '遭遇情感背叛或生离死别时心境剧震，化悲痛为苦修动力，剧情中更显坚毅苍凉。',
  },
  {
    name: '天生尤物',
    rank: '传家',
    category: '气质',
    cost: 8,
    description: '风姿绰约冠绝同侪，举手投足极具异性吸引力，容易引得高手侧目。',
    flavorPrompt: '容貌气质出众，异性NPC与之对视常有恍惚，非深仇大恨极难痛下杀手。',
  },
  {
    name: '暗解芳心',
    rank: '上乘',
    category: '天资',
    cost: 14,
    description: '极通男女幽微情愫，擅在看似坚固的姻缘中察觉裂痕，言辞信物往往能在关键时刻动摇佳人心意。',
    flavorPrompt: '剧情中擅长在关键时刻以言辞信物打动已有婚约之人，使其当众生悔或移情。',
  },
  {
    name: '夺妻之恨',
    rank: '上乘',
    category: '性情',
    cost: 14,
    description: '道侣被夺或被奸人所害后化身复仇修罗，煞气郁结于心，面对仇家时招招致命凶险。',
    attributeModifiers: { 臂力: 15 },
    flavorPrompt: '刻骨仇恨铭刻于心，面对仇敌或轻薄之徒时杀伐果断，言语冰冷绝情。',
  },
  {
    name: '红颜庇佑',
    rank: '上乘',
    category: '气质',
    cost: 14,
    description: '风姿仪态极易引动高阶异性强者的照拂庇护之意，危难关头常有绝顶高手挺身相助。',
    flavorPrompt: '面对强敌时善于示弱借势，高阶异性NPC极易产生护犊关爱之意。',
  },
  {
    name: '魏武遗风',
    rank: '镇派',
    category: '性情',
    cost: 18,
    description: '对已有家室之异性吸引力奇高，言谈举止反常地常被其伴侣视为至交好友与通家之好。',
    flavorPrompt: '在人妇或名花有主者面前魅力非凡，且其原配常常视其为生死兄弟、毫无芥蒂。',
  },
  {
    name: '绿帽神功',
    rank: '镇派',
    category: '性情',
    cost: 18,
    description: '世人的冷嘲热讽与奇耻大辱反倒成为磨砺心性的沃土，逆境中内息反常地越挫越坚。',
    attributeModifiers: { 内力: 20, 气血: 15 },
    flavorPrompt: '唾面自干心若枯井，任凭江湖流言蜚语中伤，神色自若波澜不惊。',
  },
  {
    name: '太上忘情',
    rank: '绝世',
    category: '性情',
    cost: 24,
    description: '历尽沧海斩断世俗红尘羁绊，心境无垢，参悟高深武学犹如明镜止水。',
    discounts: { savvyRequirementOffset: -3, globalUpgradeDiscount: 0.1 },
    flavorPrompt: '情至极处反归于淡漠，清冷超然，举手投足无半点凡尘情欲纠缠。',
  },
  {
    name: '倾覆天下',
    rank: '绝世',
    category: '气质',
    cost: 24,
    description: '祸水级绝色容姿，一举一动足以牵动数大宗门恩怨，群雄争相折腰。',
    flavorPrompt: '风华绝代倾国倾城，江湖豪杰、正邪掌门常为其一颦一笑而大动干戈。',
  },

  // ============================================
  // 4. 江湖性情与奇人因果
  // ============================================
  {
    name: '古灵精怪',
    rank: '粗浅',
    category: '性情',
    cost: 3,
    description: '心思活络机敏，常有天马行空的想法，善于另辟蹊径解决棘手难题。',
    flavorPrompt: '言语俏皮跳脱，行事出人意表，不喜拘泥凡俗礼节。',
  },
  {
    name: '尊师重道',
    rank: '粗浅',
    category: '性情',
    cost: 3,
    description: '极其尊敬师长门楣，门派归属感极强，深得同门长辈喜爱。',
    flavorPrompt: '行事尊奉师命规矩，言必称师门教诲，极重同门之谊。',
  },
  {
    name: '丹心侠骨',
    rank: '粗浅',
    category: '性情',
    cost: 3,
    description: '见不平之事必拔刀相助，侠肝义胆，虽易招惹麻烦却深得民间与正道赞颂。',
    flavorPrompt: '路见不平一身浩然正气，宁折不弯，侠名远播。',
  },
  {
    name: '扫地僧',
    rank: '传家',
    category: '性情',
    cost: 8,
    description: '大隐隐于市，身着朴素衣着时气质极不起眼，极擅低调自悟武学。',
    discounts: { savvyRequirementOffset: -1 },
    flavorPrompt: '平平无奇深藏不露，日常粗布麻衣扫阶除尘，无人能看穿其深浅。',
  },
  {
    name: '菩萨低眉',
    rank: '传家',
    category: '气质',
    cost: 8,
    description: '面相慈悲端庄，非血海深仇之敌极难对其生杀心，化解江湖干戈如春风化雨。',
    flavorPrompt: '神态慈和从容，言辞常具安抚人心之效，擅长化解争端。',
  },
  {
    name: '放下屠刀',
    rank: '传家',
    category: '性情',
    cost: 8,
    description: '曾造杀戮而心生忏悔皈依正道，眉宇自带度人之意，一身煞气转化为精纯定力。',
    flavorPrompt: '浪子回头金不换，眉宇间常带自省与度人之意。',
  },
  {
    name: '枯木蛰伏',
    rank: '上乘',
    category: '性情',
    cost: 14,
    description: '极擅借助环境收敛生息，耐性如铁，可为达成目的在恶劣环境下潜伏数日静候良机。',
    flavorPrompt: '耐性极佳气息如枯木，隐匿潜行时极难被旁人察觉动静。',
  },
  {
    name: '纯路人',
    rank: '上乘',
    category: '气质',
    cost: 14,
    description: '气韵平淡如微尘，走入人群或脱战数日后，寻常江湖人极易将其容貌忘得精光。',
    flavorPrompt: '五官平淡如水，走入人群瞬息无踪，NPC转头便记不清其具体样貌。',
  },
  {
    name: '言谶成非',
    rank: '上乘',
    category: '命格',
    cost: 14,
    description: '言语仿佛受无形天道反向牵引，一旦笃定断言某事，后续往往出现出人意料的离奇反转。',
    flavorPrompt: '日常聊天立下定论往往离奇逆转，惹得周围同伴提心吊胆。',
  },
  {
    name: '债多不压身',
    rank: '镇派',
    category: '命格',
    cost: 18,
    description: '欠下黑白两道巨额银两，各方债主唯恐其横死血本无归，反倒不得不在暗中保其性命周全。',
    flavorPrompt: '走到哪里都有巨额债务牵扯，债主们恨得牙痒却生怕其暴毙，常在暗中窥探甚至阻截刺客。',
  },
  {
    name: '恋爱脑',
    rank: '镇派',
    category: '性情',
    cost: 18,
    description: '一旦坠入情网便将道侣视为天地唯一，平日憨傻痴情，道侣受难受辱时狂暴武勇惊世。',
    attributeModifiers: { 臂力: 20 },
    flavorPrompt: '恋爱之时满心唯有道侣一人，痴绝入髓，谁敢犯其道侣必遭疯魔反扑。',
  },

  // ============================================
  // 5. 缺陷与负面（固定四档返还点数：-3 / -6 / -10 / -20）
  // ============================================
  // 轻度性格缺陷 (-3)
  {
    name: '贪财',
    rank: '缺陷',
    category: '缺陷',
    cost: -3,
    description: '见利忘义，爱财如命。常因蝇头小利背信弃义或身陷死地，行商采购时极易被市井奸商痛宰加价。',
    flavorPrompt: '极度贪婪吝啬，遇到黄白之物便挪不开眼，常为蝇头小利不择手段甚至临阵倒戈，口碑极差。',
  },
  {
    name: '暴躁易怒',
    rank: '缺陷',
    category: '缺陷',
    cost: -3,
    description: '性烈如火，一点即着。极易被挑衅激怒，一旦动怒便无法保持冷静，常常主动招致无谓祸端。',
    flavorPrompt: '性格暴烈如火药桶，极易遭人激将法暗算，盛怒之时不顾后果拔刀相向，处事极其鲁莽。',
  },
  {
    name: '口吃',
    rank: '缺陷',
    category: '缺陷',
    cost: -3,
    description: '天生重度结巴，舌根僵硬。急迫之时辞不达意，极易引人嗤笑，江湖言语交涉往往大受阻碍。',
    flavorPrompt: '日常交谈结巴严重，言语艰涩，任何试图化解冲突的言语交涉必定大打折扣。',
  },
  {
    name: '酒瘾',
    rank: '缺陷',
    category: '缺陷',
    cost: -3,
    description: '嗜酒如命，每日必须饮烈酒。若半日无酒便浑身发抖冷汗直冒、四肢无力，常因烂醉如泥而误事。',
    flavorPrompt: '嗜酒无度，腰间酒葫芦从不离身，无酒便狂躁手抖，醉卧街头常遭宵小洗劫。',
  },

  // 中度生理/感官缺陷 (-6)
  {
    name: '晕血',
    rank: '缺陷',
    category: '缺陷',
    cost: -6,
    description: '目睹鲜血与残肢断臂便心悸眩晕、面色惨白四肢酸软，瞬间丧失临战战意。',
    flavorPrompt: '极其畏惧腥风血雨，目睹血腥厮杀便头晕目眩战意全消，常需同伴搀扶逃命。',
  },
  {
    name: '夜盲',
    rank: '缺陷',
    category: '缺陷',
    cost: -6,
    description: '日落西山之后目力犹如瞽目盲人，眼前漆黑一片，暗夜之中伸手不见五指，极易踏空坠崖或遭伏击。',
    flavorPrompt: '入夜后双眼完全无法视物，夜间作战犹如盲打，寸步难行极易遭暗袭。',
  },
  {
    name: '骨质疏松',
    rank: '缺陷',
    category: '缺陷',
    cost: -6,
    description: '骨骼酥脆如朽木，难以承受沉重硬碰，挨上一记重拳钝击极易折伤筋骨，需久卧调养。',
    attributeModifiers: { 根骨: -15, 气血: -15 },
    flavorPrompt: '体质孱弱骨骼酥脆，挨上一记重手便吐血骨折，常年药罐不离身。',
  },

  // 重度伤残/断门缺陷 (-10)
  {
    name: '断根绝阳',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '自幼遭腐刑去势或误服奇毒断绝阳根，六根残缺，断子绝孙。身形因之阴柔迅疾，但气血底子亏损。',
    attributeModifiers: { 机敏: 10, 气血: -15 },
    flavorPrompt: '面容白皙无须，嗓音尖细清冷，举止阴柔诡谲。角色已断绝阳根，绝对无法修持纯阳、童子功类功法，亦终身断绝男女婚配与子嗣情缘。',
  },
  {
    name: '独眼',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '彻底失去一只眼珠，视野残缺一半，无纵深感，盲侧极难防备暗器与突袭。',
    attributeModifiers: { 洞察: -25 },
    flavorPrompt: '单眼遮罩黑布，转头环顾幅度极大，盲区遭遇偷袭难以防备。',
  },
  {
    name: '失聪',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '双耳永久丧失听力，天地死寂无声，无法听见脚步、风声与暗器破空。',
    attributeModifiers: { 洞察: -25 },
    flavorPrompt: '两耳失聪一片死寂，全凭目光观察口型，暗算与偷袭对其防不胜防。',
  },
  {
    name: '断臂',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '失去整条手臂，终身残废！绝对无法双持或佩戴副手兵刃盾牌，臂力与机敏大挫。',
    attributeModifiers: { 臂力: -20, 机敏: -20 },
    restrictions: {
      forbiddenEquipSlots: ['副手'],
    },
    flavorPrompt: '断袖迎风飘荡，单手持械，日常起居多有不便，战斗时缺少一手格挡。',
  },
  {
    name: '天下通缉',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '被名门正派与朝廷联合悬赏海捕，身份一旦走漏便会引来鹰犬与绿林杀手四处盘查围剿。',
    flavorPrompt: '追捕强度取决于悬赏与势力触达范围，头顶海捕文书，身份暴露极易引来围剿。',
  },
  {
    name: '内伤缠身',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '曾遭重击留下不治暗伤，每逢剧烈死斗或阴雨寒夜便真气逆冲，气血与内力上限大损。',
    attributeModifiers: { 气血: -20, 内力: -20 },
    flavorPrompt: '病骨支离面如金纸，久战必气血翻江倒海，帕掩唇角尽是殷红鲜血。',
  },
  {
    name: '天生目盲（盲侠）',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '天生双目盲瞽，不辨日月。绝对无法研读视觉武学图谱与施展暗器，全凭敏锐听觉与风息辨敌。',
    attributeModifiers: { 洞察: -30, 机敏: 10 },
    restrictions: {
      forbiddenMartialTypes: ['暗器'],
    },
    flavorPrompt: '双眼蒙布，目不能视，虽听觉警觉敏锐，但凡俗生活多有艰难。',
  },
  {
    name: '厄咒血脉',
    rank: '缺陷',
    category: '缺陷',
    cost: -10,
    description: '血脉中背负着厄运反噬之咒，气血与内力上限长期受挫，身边更容易卷入不祥因果。',
    attributeModifiers: { 气血: -15, 内力: -15 },
    flavorPrompt: '以不祥气息、身体不适和偶发厄运表现血脉诅咒，行事处处易遭天道阻遏。',
  },

  // 绝灭天残 (-20)
  {
    name: '经脉尽断',
    rank: '缺陷',
    category: '缺陷',
    cost: -20,
    description: '周天大脉彻底断绝碎裂，无法纳气归元，绝对无法修炼或运转任何内功！',
    attributeModifiers: { 内力: -50 },
    restrictions: {
      forbiddenMartialTypes: ['内功'],
    },
    flavorPrompt: '经脉寸断内息无存，无法运转内家真气，唯凭惊人毅力打磨一身外家筋骨皮肉。',
  },

  // ============================================
  // 6. 属性极限触发型特质（由初始属性极值自动赋予，无 cost）
  // ============================================
  // 臂力
  {
    name: '肌肉萎缩',
    rank: '缺陷',
    category: '缺陷',
    description: '天生四肢羸弱干瘪，肌肉严重萎缩，提拎寻常重物皆觉力不从心。',
    attributeThreshold: { attribute: '臂力', minValue: 0, maxValue: 1 },
    attributeModifiers: { 臂力: -30 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '手无缚鸡',
    rank: '缺陷',
    category: '缺陷',
    description: '体质孱弱，力气极微，甚至连抓一只鸡的气力都没有。',
    attributeThreshold: { attribute: '臂力', minValue: 2, maxValue: 5 },
    attributeModifiers: { 臂力: -15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '天生神力',
    rank: '传家',
    category: '体质',
    description: '天生臂力惊人，骨量沉实，一身神力远非同辈所能企及。',
    attributeThreshold: { attribute: '臂力', minValue: 13, maxValue: 16 },
    attributeModifiers: { 臂力: 15 },
    flavorPrompt: '腕力极沉，激动时随手捏碎瓷杯，单手搬运重物如履平地。',
  },
  {
    name: '霸王扛鼎',
    rank: '镇派',
    category: '体质',
    description: '力拔山兮气盖世，肉身神力惊世骇俗，开山裂石不在话下。',
    attributeThreshold: { attribute: '臂力', minValue: 17 },
    attributeModifiers: { 臂力: 25 },
    flavorPrompt: '臂围粗壮坚实，随手挥舞大铁锤石碾如掷稻草。',
  },

  // 根骨
  {
    name: '命若悬丝',
    rank: '缺陷',
    category: '缺陷',
    description: '先天元气大亏，体弱若惊风弱柳，稍受风寒风霜便命悬一线。',
    attributeThreshold: { attribute: '根骨', minValue: 0, maxValue: 1 },
    attributeModifiers: { 根骨: -30, 气血: -30 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '经脉淤塞',
    rank: '缺陷',
    category: '缺陷',
    description: '周天经络多处阻滞，气血与内息运转滞涩晦暗。',
    attributeThreshold: { attribute: '根骨', minValue: 2, maxValue: 5 },
    attributeModifiers: { 根骨: -15, 内力: -15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '龙精虎猛',
    rank: '传家',
    category: '体质',
    description: '精力充沛，气血旺盛如火，体魄强健宛若龙虎。',
    attributeThreshold: { attribute: '根骨', minValue: 13, maxValue: 16 },
    attributeModifiers: { 根骨: 15, 气血: 15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '武骨天成',
    rank: '镇派',
    category: '体质',
    description: '百世难遇的纯正练武胚子，经络开阔坚韧，骨骼如玉髓天成。',
    attributeThreshold: { attribute: '根骨', minValue: 17 },
    attributeModifiers: { 根骨: 25, 气血: 20, 内力: 10 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // 机敏
  {
    name: '反应迟缓',
    rank: '缺陷',
    category: '缺陷',
    description: '神思木讷，四肢动作迟滞，遇突发变故往往不及抽身规避。',
    attributeThreshold: { attribute: '机敏', minValue: 0, maxValue: 1 },
    attributeModifiers: { 机敏: -30 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '笨手笨脚',
    rank: '缺陷',
    category: '缺陷',
    description: '手脚协调欠佳，举手投足常显笨拙僵硬。',
    attributeThreshold: { attribute: '机敏', minValue: 2, maxValue: 5 },
    attributeModifiers: { 机敏: -15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '动若脱兔',
    rank: '传家',
    category: '体质',
    description: '步法轻捷迅疾，身随意转，闪展腾挪宛若脱兔。',
    attributeThreshold: { attribute: '机敏', minValue: 13, maxValue: 16 },
    attributeModifiers: { 机敏: 15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '身捷如影',
    rank: '镇派',
    category: '体质',
    description: '身法与腾挪快绝当世，动静之间犹如浮光掠影，令人难以捉摸。',
    attributeThreshold: { attribute: '机敏', minValue: 17 },
    attributeModifiers: { 机敏: 25 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // 洞察
  {
    name: '五感俱衰',
    rank: '缺陷',
    category: '缺陷',
    description: '耳目失聪、感官蒙昧，对周遭潜藏之危机暗算浑然不觉。',
    attributeThreshold: { attribute: '洞察', minValue: 0, maxValue: 1 },
    attributeModifiers: { 洞察: -30 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '视而不见',
    rank: '缺陷',
    category: '缺陷',
    description: '粗心大意，极易忽略眼皮底下的微小破绽与线索。',
    attributeThreshold: { attribute: '洞察', minValue: 2, maxValue: 5 },
    attributeModifiers: { 洞察: -15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '明察秋毫',
    rank: '传家',
    category: '天资',
    description: '目光如炬，秋毫必现，极擅在蛛丝马迹中洞悉端倪。',
    attributeThreshold: { attribute: '洞察', minValue: 13, maxValue: 16 },
    attributeModifiers: { 洞察: 15 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '洞若观火',
    rank: '镇派',
    category: '天资',
    description: '心眼通透，对全局局势与微末破绽洞悉分明，如观掌上火烛。',
    attributeThreshold: { attribute: '洞察', minValue: 17 },
    attributeModifiers: { 洞察: 25 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // 悟性
  {
    name: '浑浑噩噩',
    rank: '缺陷',
    category: '缺陷',
    description: '灵台混沌蒙昧，翻阅高深武学拳经如坠云雾。',
    attributeThreshold: { attribute: '悟性', minValue: 0, maxValue: 1 },
    discounts: { savvyRequirementOffset: 4 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '榆木脑袋',
    rank: '缺陷',
    category: '缺陷',
    description: '心思死板不知变通，研读武经招式进展甚是缓慢。',
    attributeThreshold: { attribute: '悟性', minValue: 2, maxValue: 5 },
    discounts: { savvyRequirementOffset: 2 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '聪慧过人',
    rank: '传家',
    category: '天资',
    description: '聪敏机变，参悟拳经剑谱往往能一点即通。',
    attributeThreshold: { attribute: '悟性', minValue: 13, maxValue: 16 },
    discounts: { savvyRequirementOffset: -1 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },
  {
    name: '玲珑七窍',
    rank: '镇派',
    category: '天资',
    description: '七窍玲珑，心如明镜，对天下玄奥武理往往能一通百通。',
    attributeThreshold: { attribute: '悟性', minValue: 17 },
    discounts: { savvyRequirementOffset: -3 },
    flavorPrompt: COMBAT_RULE_PROMPT,
  },

  // 风姿
  {
    name: '面目可憎',
    rank: '缺陷',
    category: '缺陷',
    description: '相貌乖戾古怪，骨相凶狞，令人望之生厌戒备。',
    attributeThreshold: { attribute: '风姿', minValue: 0, maxValue: 1 },
    flavorPrompt: '相貌凶恶古怪，初见者常退避三舍。',
  },
  {
    name: '獐头鼠目',
    rank: '缺陷',
    category: '缺陷',
    description: '神态猥琐，目光游移，容易让人心生不喜与猜忌。',
    attributeThreshold: { attribute: '风姿', minValue: 2, maxValue: 5 },
    flavorPrompt: '神态猥琐眼神闪烁，常被当成江湖宵小盘查。',
  },
  {
    name: '玉树临风',
    rank: '传家',
    category: '气质',
    description: '风度翩翩如玉树琼枝，仪态俊朗，气质卓然出众。',
    attributeThreshold: { attribute: '风姿', minValue: 13, maxValue: 16 },
    flavorPrompt: '身姿俊拔气度儒雅，驻足处常有女子悄悄注目。',
  },
  {
    name: '绝代风华',
    rank: '镇派',
    category: '气质',
    description: '姿仪神采冠绝一时，举手投足尽显风流神韵，令人过目难忘。',
    attributeThreshold: { attribute: '风姿', minValue: 17 },
    flavorPrompt: '风华绝代惊艳当世，一入客栈满堂寂然无声。',
  },

  // 福缘
  {
    name: '天煞孤星',
    rank: '缺陷',
    category: '缺陷',
    description: '命中带煞，刑克因果；同行亲近之人更容易遭逢坎坷波折。',
    attributeThreshold: { attribute: '福缘', minValue: -6, maxValue: -5 },
    flavorPrompt: '以关系波折与不祥巧合体现低福缘，不得强制亲友死亡或持续制造无法回避的灾难。',
  },
  {
    name: '霉运缠身',
    rank: '缺陷',
    category: '缺陷',
    description: '运道欠佳，日常更容易遇上小麻烦、错失与不凑巧，但不会无视现实因果制造必然灾祸。',
    attributeThreshold: { attribute: '福缘', minValue: -4, maxValue: -1 },
    flavorPrompt: '可增加合理的小倒霉和错失，不得凭空制造违反因果的致命事故。',
  },
  {
    name: '吉星高照',
    rank: '传家',
    category: '命格',
    description: '气运亨通，在合理范围内更容易遇上顺心巧合、长者照拂或转机。',
    attributeThreshold: { attribute: '福缘', minValue: 7, maxValue: 10 },
    flavorPrompt: '可在合理范围内增加巧合、善意与转机，不得凭空免死或越级化险。',
  },
  {
    name: '天命所归',
    rank: '镇派',
    category: '命格',
    description: '气运盛极，更容易被卷入天下大势、绝世机缘与时代风云之中。',
    attributeThreshold: { attribute: '福缘', minValue: 11 },
    flavorPrompt: '可让角色更容易接触重大人物、机缘与时代事件，但不得赋予“主角必胜”或凭空逆转死局的权限。',
  },
];
